### PR TITLE
Clickable read more buttons

### PR DESCRIPTION
**Pull request by patrickwalkowicz**
I've played with the previous version of the API query website and now all 'read more' buttons are clickable (so you can go back and forth between articles).

### CODE REVIEW

**Comment by patrickwalkowicz** [comment]
I've just re-written scripts using AngularJS. It's much cleaner now. @nelsonic would you mind taking a look? Thanks!

**Comment by nelsonic** [comment]
Hi @patrickwalkowicz, adding Angular is a good _personal_ learning exercise because you will come across it while working as a developer. However we prefer people to stick to "**_learn fundamentals before frameworks**_" to ensure that people understand the **_language**_ (JS). Sorry that was not _explicit_ in the Readme... @sofer thoughts?

**Comment by patrickwalkowicz** [comment]
@nelsonic thanks for your reply! In the previous version I've only used jQuery and made an API call with ajax function. However as I kept adding functionalities, I started finding the code less and less clear. This became a problem when I wanted to have functioning read more buttons that would render the whole article body. So I started experimenting with loading the content to a pre-hidden div when a button was clicked and then changing visibility of the elements. It worked but felt like [building a house of cards](https://github.com/patrickwalkowicz/MonkeyPhone/commit/fed1b0447314ba6abaf022a25fce6473923b3e1f). Then I came across AngularJS and it seemed to solve all the problems I've previously had plus enabled to do routing so each article can have a separate URL. Any suggestions on how to proceed?

**Comment by nelsonic** [comment]
@patrickwalkowicz Most _successful_ projects **_start small without a framework**_ . often people end up building their own "_micro-framework_" and _solve_ the problems you are describing incrementally as they occur. When _eventually_ the problem **_is**_ the "_in-house_" framework, then a _careful  evaluation_ of the _available_ frameworks occurs. By selecting Angular you have jumped _multiple_ steps in the journey and deprived _yourself_ of _priceless learning opportunities_. Its always _tempting_ to think that **Framework XYZ** will "_solve_" all the problems... we've _all_ been there. :wink: 

I would proceed by _mentally_ rewinding the state of the project to the point where you decided to re-implement it in Angular and write down _all_ the **_specific pain points**_ you were facing. once you have that list, start creating issues in this repo so that you know what you have to "_fix_".

Does that make sense?

**Comment by nelsonic** [comment]
Note: your efforts are _not wasted_. I simply _urge_ you to use this as a learning (_Fundamentals_) opportunity. 

[**75 Lines**](https://github.com/patrickwalkowicz/MonkeyPhone/blob/fed1b0447314ba6abaf022a25fce6473923b3e1f/js/apiquery.js) of code is an _order of magnitude_ off "_unmanageable_". The (_average_) developer can hold 200 lines of code in their working memory at any given time. I don't consider you to be "_average_". :wink: 

You can write your own "_router_" in 4 lines of code. it will be _more performant_ than Angular and writing it will teach you about _several_ interesting topics ... Writing your own framework teaches you a _lot_ and helps you understand what you are building!  Just ask @besarthoxhaj & @FilWisher

**Comment by nelsonic** [comment]
When making an "_architectural_" decision in a project, its usually (_read_: **_always**_) a good idea to create an issue to discuss it with your team _first_: https://github.com/foundersandcoders/MonkeyPhone/issues
founderscoders-monkeyphone-zero-issues

Hats off to you for being _proactive_ and learning Angular so that you could apply it to this project.
But _always_ remember that when you make a decision for a project, you are saying: "**_everyone must learn angular now**_" ... which increases the _barrier to contribution_ for other _beginners_.

**Comment by patrickwalkowicz** [comment]
@nelsonic What you wrote makes much sense. Realizing that Angular is nothing different than JS packed in an abstracted form I can learn a lot by creating something that will enable me to do the same things without an external framework.

I'll start by mapping the challenges I want to overcome and then come up with potential solutions while creating some issues to help me log the process. Discussing and thinking through architectural decisions before writing a lot of code also makes much sense.

This looks like a great learning opportunity. Thanks a lot, @nelsonic!

**Pull request closed without merging**
